[package]
name = "abap_value_mapping_creator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-win = "4.4.1"
clap = { version = "3.1.12", features = ["derive"]}
